body:
  - type: textarea
    attributes:
      name: webhooks
      label: Saved Webhooks
      description: >
        This text will be added to the beginning of the result output. For example, if you set this to 
        "The result is: ", and the result is "42", the output will be "The result is: 42". 