body:
  - type: textarea
    attributes:
      name: webhooks
      label: Saved Webhooks
      description: >
        Each line will be treated as its own webhook, with the following format: `name!url`
        for example: `foo!https://ptb.discord.com/api/webhooks/1348721137839902741/tvQaNfMS917XypWj7fSskiASiKK5ovxMwDeNU-6_GIjeIQu-rBvFuoor_pUfealHCXai`